# Generated by Django 3.2.12 on 2022-04-01 14:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aquarium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_aquarium', models.CharField(max_length=20)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Donnee_date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donnee_date', models.DateField()),
                ('aquarium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aquarium.aquarium')),
            ],
        ),
        migrations.CreateModel(
            name='Donnee_releve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_donnee_releve', models.CharField(max_length=15)),
                ('donnee_releve', models.IntegerField()),
                ('donnee_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aquarium.donnee_date')),
            ],
        ),
        migrations.CreateModel(
            name='Donnee_note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donnee_note', models.CharField(max_length=200)),
                ('donnee_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aquarium.donnee_date')),
            ],
        ),
    ]
