# Generated by Django 3.2.12 on 2022-04-01 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquarium', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='aquarium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_aquarium', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
