# Generated by Django 3.2.12 on 2022-04-01 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquarium', '0002_auto_20220401_1110'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donnee_date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donnee_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Donnee_note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donnee_note', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Donnee_releve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_donnee_releve', models.CharField(max_length=15)),
                ('donnee_releve', models.IntegerField()),
            ],
        ),
    ]
